Chat/urls.py
from django.urls import path
from . import views

app_name = 'Chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('start_chat/<str:second_user>', views.start_chat, name='start_chat'),
    path('<str:room_name>/', views.room, name='room'),
    path('message/delete/<int:id>/', views.delete_message, name='delete_message'),
]

Task/urls.py
from django.urls import path
from .views import TaskCreate, TaskDelete, TaskIndex, TaskListDelete, TaskUpdate, Done_or_Not

app_name = 'Task'

urlpatterns = [
    path("", TaskIndex, name="index"),
    path("task/create/", TaskCreate, name="task_create"),
    path("task/update/<slug>/", TaskUpdate, name="update"),
    path("task/delete/<slug>/", TaskDelete, name="delete"),
    path("task/delete/all/<slug>/", TaskListDelete, name="task_delete_all"),
    path("task/done_or_not/<slug>/", Done_or_Not, name="done_or_not"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import Explore, Notifications, Settings, CategoryCreate, CategoryDelete, CategoryListDelete, GoalCreate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User.urls')),
    path('friendship/', include('Friendship.urls')),
    path('group/', include('Group.urls')),
    path('chat/', include('Chat.urls')),
    path('', include('Task.urls')),
    path('pomodoro/', include('Pomodoro.urls')),
    path('addiction/', include('Addiction.urls')),
    path('explore/', Explore, name = 'explore'),
    path('settings/<slug>/', Settings, name = 'settings'),
    path('notifications/<slug>/', Notifications, name = 'notifications'),
    path('category/create/', CategoryCreate, name = 'category_create'),
    path('category/delete/', CategoryDelete, name = 'category_delete'),
    path('category/list/delete/', CategoryListDelete, name = 'category_list_delete'),
    path('goal/create/', GoalCreate, name = 'goal_create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Task/models.py
from django.db import models
from django.http.response import HttpResponse, JsonResponse
from User.models import CustomUser
from django.urls import reverse
from django.utils.text import slugify
import datetime 

class Category(models.Model):
    PRIORITY_CHOICES = (
        ('None', '-'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
    )
    title = models.CharField(max_length=100)
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='gray')
    slug = models.SlugField(unique=True, editable=False)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)

    def get_delete_url(self):
        return reverse('User:category_delete')

    def get_unique_slug(self):
        number = 0
        original_slug = '%s %s' % (self.title.replace('ı', 'i'), (self.user.username.replace('ı','i')))
        unique_slug = slugify(original_slug)
        while Category.objects.filter(slug = unique_slug).exists():
            number += 1
            unique_slug = '%s %d' % (original_slug, number)
            unique_slug = slugify(unique_slug)
        return unique_slug

    def __str__(self):
        return '%s' % self.title

    def save(self, *args, **kwargs):
        self.slug = self.get_unique_slug()
        return super(Category, self).save(*args, **kwargs)

class Task(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False)
    done = models.BooleanField(default=False)
    score = models.PositiveIntegerField(default = 0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category', null=True, blank=True)    
    message = models.TextField(editable=False)
    created_time = models.DateTimeField(null=True, blank=True)
    updated_time = models.DateTimeField(null=True, blank=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)

    def get_unique_slug(self):
        number = 0
        original_slug = '%s' % (self.title.replace('ı', 'i'))
        unique_slug = slugify(original_slug)
        while Task.objects.filter(slug = unique_slug).exists():
            number += 1
            unique_slug = '%s %d' % (original_slug, number)
            unique_slug = slugify(unique_slug)
        return unique_slug

    def done_or_not(self):
        return reverse('Task:done_or_not', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('Task:delete', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = self.get_unique_slug()
            self.created_time = datetime.datetime.now()
            self.updated_time = datetime.datetime.now()
        else:
            self.updated_time = datetime.datetime.now()
        if self.done == True:
            if self.category:
                if self.category.priority == '1':
                    self.score = 10
                elif self.category.priority == '2':
                    self.score = 10
                elif self.category.priority == '3':
                    self.score = 10
                else:
                    self.score = 10
            else:
                self.score = 10
        else:
            self.score = 0
        return super(Task, self).save(*args, **kwargs)  

Task/views.py
from django.contrib.auth import login
from django.core.exceptions import ValidationError
from django.http.response import HttpResponseBadRequest, HttpResponseRedirect, JsonResponse, HttpResponseForbidden
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.contrib import messages
from django.http import HttpResponse
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from Friendship.models import Friendship
from User.models import CustomUser
from .models import Category, Task
import datetime

def TaskIndex(request):
    if not request.user.is_authenticated:
        return render(request, 'task/index.html')
    else:        
        #Kullanıcıya Ait Görevler
        current_user = request.user
        total_score = 0
        task_list = current_user.task_set.all()
        #Görevin süresinin üzerinden 24 saat geçince kendisini silmesi
        for task in task_list:
            if datetime.datetime.now().day == task.created_time.day+1:
                task.delete()
                return redirect('Task:index')
                 
        #Her Sayfada 6 Max. Görev Gösterme       
        paginator = Paginator(task_list, 5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        #Günlük Puanı Getirir
        total_score = current_user.get_day_score()
        
        #Kullanıcıya ait kategorileri gösterme
        category_list = Category.objects.filter(user=request.user)
        context = {
            'page_obj': page_obj,
            'total_score': total_score,
            'category_list': category_list,
        }
        return render(request, 'task/index.html', context)


@login_required(login_url='User:login')
def TaskCreate(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            title = request.POST.get('title', None)
            category = request.POST.get('category', None)
            done = request.POST.get('done', None)
            if (title != None and title != '') and (done != None and done != '') and (category != None and category != ''):
                raise ValidationError('Boş bırakılamaz!')
            if done == 'on':
                done = True
            else:
                done = False

            #Başlık 66 Karakterden Fazla Olursa Hata Vermesi
            if len(title) > 66:
                raise ValidationError('66 karakterden fazla yazamazsın!')
            if category == None:
                new_task = Task.objects.create(title = title, done = done, user = request.user)
            else:
                category = Category.objects.get(user=request.user, title=category)
                new_task = Task.objects.create(title = title, done = done, category=category, user = request.user)
            
            #Önem Derecesine Göre Renk Atama
            messages.info(request, 'Görevi oluşturdun! Bitir, puan kazan ve hedefine yaklaş!')
            return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
    else:
        return HttpResponseForbidden()
        
@login_required(login_url='User:login')
def TaskUpdate(request, slug):
    task = get_object_or_404(Task, slug = slug)
    if task.user == request.user:
        if request.method == "POST":
            title_update = request.POST.get('title_update', None)
            done_update = request.POST.get('done_update', None)
            category_update = request.POST.get('category_update', None)
            if done_update != None:
                done_update = True
            else:
                done_update = False   
            if len(title_update) > 66:
                raise ValidationError('66 karakterden fazla yazamazsın!')
            task.title = title_update
            task.done = done_update
            if category_update == None:
                task.category = None
            else:
                category_update = Category.objects.get(user=request.user, title__icontains=category_update)
                task.category = category_update
            task.save()
            return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
        else:
            update_category_list = Category.objects.all()
            print(update_category_list)
            if task.category in update_category_list:
                update_category_list = Category.objects.all().exclude(task.category)
            print(update_category_list)
            return JsonResponse(update_category_list, safe=False)
    else:
        return HttpResponseForbidden()

@login_required(login_url='User:login')
def TaskDelete(request, slug):
    task = get_object_or_404(Task, slug=slug)
    if task.user == request.user:
        task.delete()
    else:
        return HttpResponseForbidden()
    return JsonResponse('Deleted!', safe=False)

@login_required(login_url='User:login')
def TaskListDelete(request, slug):
    if request.user.username == slug:
        current_user = request.user
        task_list = Task.objects.filter(user=current_user)
        task_list.delete()
        return redirect('Task:index')
    else:
        return HttpResponseForbidden()

@login_required(login_url='User:login')
def Done_or_Not(request, slug):
    task = get_object_or_404(Task, slug=slug)
    if task.user == request.user:
        task_title = ''
        if task.done == True:
            task.done = False
        else:
            task.done = True
        task.save()
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
    else:
        return HttpResponseForbidden()

Task/templates/task/index.html
{% extends 'base.html' %} {% block title %} Todo List {% endblock %} {% block style %} {% endblock %} {% block content %}
<div class="container">

    {% if messages %} {% for message in messages %}
    <div id="special_message"></div>
    <div class="alert text-center alert-{% if message.tags == 'warning' %}danger{% else %}{{message.tags}}{% endif %} alert-dismissible fade show">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
         <span aria-hidden="true">&times;</span>
         <span class="sr-only">Close</span>
     </button> {{message}}
    </div>
    {% endfor %} {% endif %}

    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-8">
            {% if request.user.is_authenticated %}
            <div id="progress" style="background-color: #ddd !important;position: relative !important;height: 30px !important;width: 100% !important; border-radius: 5px !important;            cursor: default;">
                <div id="bar" style="background-color: #4CAF50 !important;width: 5px !important;height: 30px !important;position: absolute !important; border-radius: 5px !important;"><span class="lead ml-2 text-white">Verim</span></div>
            </div>
            {% endif %}
            <!--Modal Create Open Button-->
            <div class="row mt-3" id="task_create_button_collapse">
                <div id="task_create_button_div">
                    <button id="task_create_button" name='create' type="button" class="btn btn-outline-dark btn-md" data-toggle="modal" data-target="#taskCreateModal">
                +
                </button>
                </div>
            </div>
            <!-- Modal Task Create-->
            <div class="modal fade" id="taskCreateModal" tabindex="-1" role="dialog" aria-labelledby="taskCreateModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="taskCreateModalLabel">Yeni Görev</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                        </div>
                        <div class="modal-body">
                            <form id="task_create_form" class="form-group" action="{% url 'Task:task_create' %}" method="POST">
                                {% csrf_token %}
                                <div class="form-title">
                                    <label class="label" for="title">Başlık</label><input onclick="LetterCountCreate()" id="task_title_input" class="form-control" name="title" type="text">
                                    <span class="mt-1" id="letters"></span>
                                </div>
                                <div class="form-done d-flex form-inline mt-4">
                                    <label class="label" for="done">Bitti mi?</label><input class="form-control ml-3" name='done' type="checkbox">
                                </div>
                                <div class="form-category d-flex form-group mt-4">
                                    <div class="row w-100 mt-2 d-flex justify-content-center">
                                        {% for category in category_list %}
                                        <div class="col-md-3 d-inline" id="category_box">
                                            <label class="label d-block" for="{{category}}">{{category}}</label>
                                            <input id="category" name="category" class="form-control d-block" value="{{category}}" type="radio">
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-dark">Görev Oluştur</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!--Task List-->
            {% for task in page_obj %} {% if task.message %} {{task.message|safe}} {% else %} {% endif %} {% if task.category.priority == '1' %}
            <!--Kategorilerin Önem Derecesine Göre Görevleri Renklendirme
                 1-Mavi 2-Yeşil 3-Turuncu 4-Gri -->
            <div id="task{{task.slug}}" style="border-left: 3px solid #0299bb !important;" class="card-header mt-2">
                {% elif task.category.priority == '2' %}
                <div id="task{{task.slug}}" style="border-left: 3px solid #00ad35 !important;" class="card-header mt-2">
                    {% elif task.category.priority == '3' %}
                    <div id="task{{task.slug}}" style="border-left: 3px solid #e47423 !important;" class="card-header mt-2">
                        {% else %}
                        <div id="task{{task.slug}}" style="border-left: 3px solid gray !important;" class="card-header mt-2">
                            {% endif %}
                            <div class="row">
                                <div class="col-md-6">
                                    <span id="task_title" ondblclick="TaskUpdate('{{task.slug}}')" class="lead">{{task.title}}</span>
                                </div>
                                <div id="done_or_not_button_div" class="col-md-3">
                                    {% if task.done == False %}
                                    <a id="done_or_not_button_yellow" href="{{task.done_or_not}}" type="button" class="btn">Tamamla</a> {% else %}
                                    <a id="done_or_not_button_green" href="{{task.done_or_not}}" type="button" class="btn btn-success">Bitirme</a> {% endif %}
                                </div>
                                <div id="delete_button_div" class="col-md-3 d-flex justify-content-end">
                                    <a onclick="TaskDelete('{{ task.slug }}')" id='{{task.slug}}' url="{% url 'Task:delete' slug=task.slug %}" id="delete_button" type="button" class="btn btn-outline-danger text-danger delete_button">Sil</a>
                                </div>

                            </div>
                        </div>
                        <!--Modal Task Update-->
                        <div class="modal fade" id='done{{task.slug}}' tabindex="-1" role="dialog" aria-labelledby="taskUpdateModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="{{task.slug}}">Görev Güncelleme</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                    </button>
                                    </div>
                                    <div class="modal-body">
                                        <form id='task_update_form' class="form-group" action="{% url 'Task:update' slug=task.slug %}" method="POST">
                                            {% csrf_token %}
                                            <div class="form-title">
                                                <label class="label" for="title">Başlık</label><input onclick="LetterCountUpdate('{{task.slug}}')" id="task_title_input{{task.slug}}" value='{{task.title}}' class="form-control" name="title_update" type="text">
                                                <span class="mt-1" id="letters{{task.slug}}"></span>
                                            </div>
                                            <div class="form-done d-flex form-inline mt-4">
                                                <label class="label" for="done">Bitti mi?</label> {% if task.done == True %}
                                                <input name='done_update' checked value='on' class="form-control ml-3" type="checkbox"> {% else %} <input value='off' class="form-control ml-3" name='done_update' type="checkbox">{% endif %}
                                            </div>
                                            <div class="form-category d-flex form-group mt-4">
                                                {% for category in category_list %}
                                                <div class="row w-100">
                                                    <label class="label col-md-9" for="{{category}}">{{category}}</label>
                                                    <input id="category_update" name="category_update" class="form-control ml-4 col-md-3" value="{{category}}" type="radio">
                                                </div>{% endfor %}
                                            </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button onclick="TaskUpdateForm()" type="submit" class="btn btn-dark">Görevi Güncelle</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {% endfor %} {% if page_obj.has_other_pages %}
                        <nav>
                            <ul class="pagination mt-1">
                                {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link border-primary" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                                </li>
                                {% endif %} {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link border-primary" href="?page={{ page_obj.next_page_number }}">Next</a>
                                </li>
                                {% endif %}
                            </ul>
                        </nav>
                        {% endif %}

                        <!--Secret Section(Goal and Total Score)-->
                        <div class="col-md-1 d-flex justify-content-center" style="display: none !important;">
                            <span id="total_score" style="display: none !important;">{{total_score}}</span> {% if request.user.goal_score != 0 %}
                            <div id="goal" style="display: none !important;">{{request.user.goal_score}}</div>
                            {% endif %}
                        </div>



                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}