Chat/urls.py
from django.urls import path
from . import views

app_name = 'Chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('start_chat/<str:second_user>', views.start_chat, name='start_chat'),
    path('<str:room_name>/', views.room, name='room'),
    path('message/delete/<int:id>/', views.delete_message, name='delete_message'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import Explore, Notifications, Settings, CategoryCreate, CategoryDelete, CategoryListDelete, GoalCreate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User.urls')),
    path('friendship/', include('Friendship.urls')),
    path('group/', include('Group.urls')),
    path('chat/', include('Chat.urls')),
    path('', include('Task.urls')),
    path('pomodoro/', include('Pomodoro.urls')),
    path('addiction/', include('Addiction.urls')),
    path('explore/', Explore, name = 'explore'),
    path('settings/<slug>/', Settings, name = 'settings'),
    path('notifications/<slug>/', Notifications, name = 'notifications'),
    path('category/create/', CategoryCreate, name = 'category_create'),
    path('category/delete/', CategoryDelete, name = 'category_delete'),
    path('category/list/delete/', CategoryListDelete, name = 'category_list_delete'),
    path('goal/create/', GoalCreate, name = 'goal_create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Chat/models.py
from django.db import models
from User.models import CustomUser
import uuid


class Room(models.Model):
    room_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    first_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='room_first_user', null=True)
    second_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='room_second_user', null=True)

class Message(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='user', verbose_name='Kullanıcı', null=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='room', verbose_name='Oda', null=True)
    content = models.TextField(verbose_name='Mesaj İçeriği')
    is_seen = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)

    def get_short_date(self):
        created_date = str(self.created_date.hour+3) + ":" + str(self.created_date.minute)
        return created_date

User/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse

class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatar/', default='avatar/default.png')
    friends = models.ManyToManyField('self', related_name='friends', blank=True)
    score = models.PositiveIntegerField(default=0)
    goal_score = models.PositiveIntegerField(default=0)
    daily_score = models.PositiveIntegerField(default=0)
    last_login = models.DateTimeField(null=True, auto_now=True)

    def get_friends_count(self):
        friends_count = self.friends.count()
        print(friends_count)
        return friends_count

    def get_day_score(self):
        total_score = 0
        for task in self.task_set.all():
            total_score += task.score  
        try:
            print(self.daily_score)
            self.daily_score = int(total_score) / int(self.goal_score * 10)
            self.daily_score = int(self.daily_score * 100)
            self.save()
        except:
            self.daily_score = 1
        return self.daily_score

    
    def __str__(self):
        return '%s' % (self.username)

    def save(self ,*args ,**kwargs):
        return super(CustomUser, self).save(*args, **kwargs)


class Profile(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)

    def get_logout_url(self):
        return reverse('User:logout')

    def get_custom_user_settings(self):
        return reverse('User:settings', kwargs={'slug': self.slug})

    def get_absolute_url(self):
        return reverse('User:profile', kwargs={'slug': self.slug})

    def get_unique_slug(self):
        number = 0
        original_slug = '%s' % (self.user.username.replace('ı','i'))
        unique_slug = slugify(original_slug)
        while Profile.objects.filter(slug = original_slug).exists():
            number += 1
            unique_slug = '%s %d' % (original_slug, number)
            unique_slug = slugify(unique_slug)
        return unique_slug

    def __str__(self):
        return "%s's Profile" % (self.user.username)
    
    def save(self, *args , **kwargs):
        self.slug = self.get_unique_slug()
        return super(Profile, self).save(*args, **kwargs)

@receiver(post_save, sender=CustomUser)
def post_save_create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
post_save.connect(post_save_create_profile, sender=CustomUser)    





Chat/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseForbidden
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth import login
from User.models import CustomUser
from .models import Room, Message

@login_required(login_url='User:login')
def index(request):
    if not request.user.is_authenticated:
        return redirect('User:login')
    user_list = request.user.friends.all()
    rooms = Room.objects.filter(Q(first_user=request.user) | Q(second_user=request.user))
    room_message_list = []
    room_message_owners = []
    for room in rooms:
        room_message_list = Message.objects.filter(room=room, is_seen=False).exclude(user=request.user)
        for room_message in room_message_list:
            if room_message.user in room_message_owners:
                pass
            else:
                room_message_owners.append(room_message.user)
    return render(request, 'chat/index.html', {'user_list': user_list, 'room_message_owners': room_message_owners})

@login_required(login_url='User:login')
def start_chat(request, second_user):
    if not request.user.is_authenticated:
        return redirect('User:login')    
    second_user = CustomUser.objects.get(username=second_user)
    print(second_user)
    try:
        room = Room.objects.get(first_user=request.user, second_user=second_user)
    except Room.DoesNotExist:
        try:
            room = Room.objects.get(second_user=request.user, first_user=second_user)
        except:
            room = Room.objects.create(first_user=request.user, second_user=second_user)
    return redirect('Chat:room', room.room_id)

@login_required(login_url='User:login')
def room(request, room_name):
    if not request.user.is_authenticated:
        return redirect('User:login')        
    user_list = request.user.friends.all()
    room = Room.objects.get(room_id=room_name)
    message_list = Message.objects.filter(room=room)    
    for message in message_list:
        message.is_seen = True
        message.save()
    rooms = Room.objects.filter(Q(first_user=request.user) | Q(second_user=request.user))
    room_message_list = []
    room_message_owners = []
    for item in rooms:
        room_message_list = Message.objects.filter(room=room, is_seen=False).exclude(user=request.user)
        for room_message in room_message_list:
            if room_message.user in room_message_owners:
                pass
            else:
                room_message_owners.append(room_message.user)
    return render(request, 'chat/chat_room.html', {
        'room_name': room_name, 'room': room, 'user_list': user_list, 'message_list': message_list, 'room_message_owners': room_message_owners
    })

@login_required(login_url='User:login')
def delete_message(request, id):
    message = Message.objects.get(user=request.user, id=id)
    if message.user == request.user:
        room_name = message.room.room_id
        message.delete()
        return redirect('Chat:room', room_name)
    else:
        return HttpResponseForbidden()

Chat/templates/chat/chat_room.html
{% extends 'base.html' %} {% load static %} {% block title %}Kişiler{% endblock title %} {% block content %}
<div class="container-fluid pl-0 pr-0 mt-0 pt-0">
    <div class='row d-flex justify-content-end align-items-end'>
        <a href="{% url 'Chat:index' %}" class="btn btn-outline-danger" id="back_to_chat_index">&larr;</a>
    </div>
    <div id="chat_room_main" class="row d-flex justify-content-between">
        <div class="col-md-4 people_collapse_chat_room pl-0 pr-0" style="border-right: 1px solid black !important;" id="people_collapse">
            <div class="card-header d-flex justify-content-center align-items-center font-weight-bold mt-0" style="height: 70px !important; font-size: 26px !important;font-family: 'Roboto', sans-serif;">Arkadaşlar</div>
            {% for user in user_list %}
            <a id="people_link" href="{% url 'Chat:start_chat' user.username %}" style="text-decoration: none !important;">
                <div id="people" class="card-header d-flex align-items-center justify-content-between text-white">
                    {% if user in room_message_owners %}
                    <div class="w-75"><img id="person_image" class="rounded-circle" src="{{user.avatar.url}}">|<span class="font-weight-bold">{{user.username}}</span><small class="font-weight-bold ml-2 text-warning" style="font-size: 13.5px !important;">- Mesaj</small></div>
                    {% else %}
                    <div class="w-75"><img id="person_image" class="rounded-circle" src="{{user.avatar.url}}">|<span>{{user.username}}</span></div>
                    {% endif %} {%if user.last_login != None %}
                    <div style="font-size: 14px !important;">{{ user.last_login|timesince }} önce</div>{% endif%}</div>
            </a>
            {% endfor %}
        </div>
        <div id="chat" class="col-md-8 pl-0">
            {% if room.first_user == request.user %}
            <div id="chat_person" class="card-header d-flex align-items-center text-white">
                <a href="{{room.second_user.profile_set.get.get_absolute_url}}" class="card-link text-white">
                    <img style="width: 15% !important" class="rounded-circle" src="{{ room.second_user.avatar.url }}" alt=""> | {{ room.second_user }}</span>
                </a>
            </div>
            {% else%}
            <div id="chat_person" class="card-header d-flex align-items-center text-white">
                <a href="{{room.first_user.profile_set.get.get_absolute_url}}" class="card-link text-white">
                    <img style="width: 15% !important" class="rounded-circle" src="{{ room.first_user.avatar.url }}" alt=""> | {{ room.first_user }}</span>
                </a>
            </div>
            {% endif %}
            <div id="messages">
                {% for message in message_list %} {% if message.user == request.user %}
                <div class="row mt-2 mr-2 d-flex justify-content-end">
                    <div id="time" class='d-flex align-items-end'>
                        <small class="mb-1 mr-1 ">{{ message.get_short_date }}</small>
                    </div>
                    <div class="card-header pr-2 pl-2" id="message_box1">
                        <div style="word-wrap: break-word;">{{message.content}}</div>
                    </div>
                    <div id="details" style="font-size: 12px;" class="d-flex align-items-end ml-1"><a href="{% url 'Chat:delete_message' message.id %}" class="text-danger font-weight-bold">x</a></div>
                </div>
                {% else %}
                <div class="row mt-2 ml-2">
                    <div class="card-header" id="message_box2">
                        <div style="word-wrap: break-word;">{{message.content}}</div>
                    </div>
                    <div id="time" class="d-flex align-items-end"><small class="float-left mb-1 ml-1">{{ message.get_short_date }}</small></div>
                </div>
                {% endif %} {% endfor %}
            </div>
            <div id="message_inputs" class="card-footer d-flex align-items-center">
                <div class="d-flex justify-content-center w-100 m-0 p-0">
                    <input id="message_input" class="form-control" type="text">
                </div>
                <i id="send" class="fa fa-paper-plane text-dark ml-auto mr-4"></i>
            </div>
        </div>
    </div>
</div>
{{ room_name|json_script:"room-name" }} {{ request.user.username|json_script:"user" }}
<script>
    const roomName = JSON.parse(document.getElementById("room-name").textContent);
    const user = JSON.parse(document.getElementById('user').textContent);
    const conversation = document.getElementById('messages');
    const chatSocket = new WebSocket("ws://" + window.location.host + "/ws/chat/" + roomName + "/");
    const sendButton = document.getElementById('send');
    const input = document.getElementById('message_input');

    var isRecord = false

    chatSocket.onmessage = function(e) {
        conversation.scrollTop = conversation.scrollHeight
        const data = JSON.parse(e.data)
        console.log(data.created_date)
        if (user == data.user) {
            var message = '<div class="row mt-2 mr-2 d-flex justify-content-end"><div id="time" class="d-flex align-items-end"><small class="float-left mb-1 mr-1">' + data.created_date + '</small></div><div class="card-header" id="message_box1">' + data.message + '<i class="fa fa-settings"></i></div></div>'
        } else {
            var message = '<div class="row mt-2 ml-2"><div class="card-header" id="message_box2">' + data.message + '</div><div id="time" class="d-flex align-items-end"><small class="float-left mb-1 ml-1">' + data.created_date + '</small></div></div>'
        }
        conversation.innerHTML += message;
        conversation.scrollTop = conversation.scrollHeight
    }
    chatSocket.onclose = function(e) {
        console.error('Socket beklenmedik bir şekilde kapandı!')
    }
    input.onkeyup = function(e) {
        if (e.keyCode === 13) {
            sendButton.click();
        }
    }
    sendButton.onclick = function(e) {
        const message = input.value;
        chatSocket.send(JSON.stringify({
            'message': message,
        }))
        input.value = '';
    }
    conversation.scrollTop = conversation.scrollHeight
</script>
{% endblock content %}

Chat/templates/chat/index.html
{% extends 'base.html' %} {% load static %} {% block title %}Kişiler{% endblock title %} {% block content %}
<div class="container-fluid pl-0 pr-0 mt-0 pt-0">

    <div class="row d-flex justify-content-between">
        <div class="col-md-4 people_collapse_chat_room pl-0 pr-0" style="border-right: 1px solid black !important;" id="people_collapse">
            <div class="card-header d-flex justify-content-center align-items-center mt-0" style="height: 70px !important; font-size: 26px !important;font-family: 'Roboto', sans-serif;">Arkadaşlar</div>
            {% for user in user_list %}
            <a id="people_link" href="{% url 'Chat:start_chat' user.username %}" style="text-decoration: none !important;">
                <div id="people" class="card-header d-flex align-items-center justify-content-between text-white">
                    {% if user in room_message_owners %}
                    <div class="w-50"><img id="person_image" class="rounded-circle" src="{{user.avatar.url}}">|<span class="font-weight-bold">{{user.username}}</span><small class="font-weight-bold ml-2 text-warning" style="font-size: 13.5px !important;">- Mesaj</small></div>
                    {% else %}
                    <div class="w-50"><img id="person_image" class="rounded-circle" src="{{user.avatar.url}}">|<span>{{user.username}}</span></div>
                    {% endif %} {%if user.last_login != None %}
                    <div style="font-size: 14px !important;">{{ user.last_login|timesince }} önce</div>{% endif%}</div>
            </a>
            {% endfor %}
        </div>
        <div id="chat" class="col-md-8 pl-0" style="width: 60% !important; background-color: rgb(226, 226, 226) !important;">
        </div>
    </div>
</div>
{{ room_name|json_script:"room-name" }}
<script>
    const roomName = JSON.parse(document.getElementById("room-name").textContent);
    const conversation = document.getElementById('messages')
    const chatSocket = new WebSocket("ws://" + window.location.host + "/ws/chat/" + roomName + "/")
    const sendButton = document.getElementById('send')
    const input = document.getElementById('message_input')

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data)
        var message = '<div class="row mt-2 ml-2"><div class="card-header" id="message_box">' + data.message + '</div><div id="time" class="d-flex align-items-end"><small class="float-left mb-1 ml-1">Bugün</small></div></div>'
        conversation.innerHTML += message;
    }
    chatSocket.onclose = function(e) {
        console.error('Socket beklenmedik bir şekilde kapandı!')
    }
    input.focus();
    input.onkeyup = function(e) {
        if (e.keyCode === 13) {
            sendButton.click();
        }
    }
    sendButton.onclick = function(e) {
        const message = input.value;
        chatSocket.send(JSON.stringify({
            'message': message,
        }))
    }
</script>
{% endblock content %}