Chat/urls.py
from django.urls import path
from . import views

app_name = 'Chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('start_chat/<str:second_user>', views.start_chat, name='start_chat'),
    path('<str:room_name>/', views.room, name='room'),
    path('message/delete/<int:id>/', views.delete_message, name='delete_message'),
]

Friendship/urls.py
from django.urls import path
from .views import send_request, accept_request

app_name = 'Friendship'

urlpatterns = [
    path("send_request/<slug>/", send_request, name="send_request"),
    path("accept_request/<slug>/", accept_request, name="accept_request"),
]

Task/urls.py
from django.urls import path
from .views import TaskCreate, TaskDelete, TaskIndex, TaskListDelete, TaskUpdate, Done_or_Not

app_name = 'Task'

urlpatterns = [
    path("", TaskIndex, name="index"),
    path("task/create/", TaskCreate, name="task_create"),
    path("task/update/<slug>/", TaskUpdate, name="update"),
    path("task/delete/<slug>/", TaskDelete, name="delete"),
    path("task/delete/all/<slug>/", TaskListDelete, name="task_delete_all"),
    path("task/done_or_not/<slug>/", Done_or_Not, name="done_or_not"),
]

User/urls.py
from .views import CustomUserLogin, RegisterCustomUser, CustomUserProfile, UpdateCustomUser
from django.contrib.auth.views import LogoutView
from django.urls import path

app_name = 'User'

urlpatterns = [
    path('register/', RegisterCustomUser, name = 'register'),
    path('update/<slug>/', UpdateCustomUser, name = 'update'),
    path('profile/<slug>/', CustomUserProfile, name = 'profile'),
    path('login/', CustomUserLogin, name = 'login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name = 'logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import Explore, Notifications, Settings, CategoryCreate, CategoryDelete, CategoryListDelete, GoalCreate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User.urls')),
    path('friendship/', include('Friendship.urls')),
    path('group/', include('Group.urls')),
    path('chat/', include('Chat.urls')),
    path('', include('Task.urls')),
    path('pomodoro/', include('Pomodoro.urls')),
    path('addiction/', include('Addiction.urls')),
    path('explore/', Explore, name = 'explore'),
    path('settings/<slug>/', Settings, name = 'settings'),
    path('notifications/<slug>/', Notifications, name = 'notifications'),
    path('category/create/', CategoryCreate, name = 'category_create'),
    path('category/delete/', CategoryDelete, name = 'category_delete'),
    path('category/list/delete/', CategoryListDelete, name = 'category_list_delete'),
    path('goal/create/', GoalCreate, name = 'goal_create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse

class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatar/', default='avatar/default.png')
    friends = models.ManyToManyField('self', related_name='friends', blank=True)
    score = models.PositiveIntegerField(default=0)
    goal_score = models.PositiveIntegerField(default=0)
    daily_score = models.PositiveIntegerField(default=0)
    last_login = models.DateTimeField(null=True, auto_now=True)

    def get_friends_count(self):
        friends_count = self.friends.count()
        print(friends_count)
        return friends_count

    def get_day_score(self):
        total_score = 0
        for task in self.task_set.all():
            total_score += task.score  
        try:
            print(self.daily_score)
            self.daily_score = int(total_score) / int(self.goal_score * 10)
            self.daily_score = int(self.daily_score * 100)
            self.save()
        except:
            self.daily_score = 1
        return self.daily_score

    
    def __str__(self):
        return '%s' % (self.username)

    def save(self ,*args ,**kwargs):
        return super(CustomUser, self).save(*args, **kwargs)


class Profile(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)

    def get_logout_url(self):
        return reverse('User:logout')

    def get_custom_user_settings(self):
        return reverse('User:settings', kwargs={'slug': self.slug})

    def get_absolute_url(self):
        return reverse('User:profile', kwargs={'slug': self.slug})

    def get_unique_slug(self):
        number = 0
        original_slug = '%s' % (self.user.username.replace('ı','i'))
        unique_slug = slugify(original_slug)
        while Profile.objects.filter(slug = original_slug).exists():
            number += 1
            unique_slug = '%s %d' % (original_slug, number)
            unique_slug = slugify(unique_slug)
        return unique_slug

    def __str__(self):
        return "%s's Profile" % (self.user.username)
    
    def save(self, *args , **kwargs):
        self.slug = self.get_unique_slug()
        return super(Profile, self).save(*args, **kwargs)

@receiver(post_save, sender=CustomUser)
def post_save_create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
post_save.connect(post_save_create_profile, sender=CustomUser)    





templates/other_templates/explore.html
{% extends 'base.html' %} {% block title %} Keşif {% endblock %} {% block style %} {% endblock %} {% block content %}
<div class="container">

    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-6 float-left" style="border-right: 1px solid black !important;">
            <form class="form-inline" method="GET">
                <input name="user_input" id="user_input" placeholder="Kişi ara..." class="form-control w-75 p-2" type="search">
                <button id="user_search_button" type="submit" class="btn btn-dark ml-2">Ara</button>
            </form>
            {% if users %} {% for user in users %}
            <a href="{{user.profile_set.get.get_absolute_url}}" style="text-decoration: none !important; color: black !important;">
                <div id='filtered_user' class="card-header text-white rounded mt-2" style="background-color: black !important;"><img class="rounded-circle" style="width: 15% !important;" src="{{user.avatar.url}}" alt=""> | {{user}}</div>
            </a>
            {% endfor %} {% endif %}
        </div>
        <div class="col-md-6 float-right">
            <form class="form-inline" method="GET">
                <input name="group_input" id="user_input" placeholder="Grup ara..." class="form-control w-75 p-2" type="search">
                <button id="group_search_button" type="submit" class="btn btn-dark ml-2">Ara</button>
            </form>
            {% if groups %} {% for group in groups %}
            <a href="{{group.get_absolute_url}}" style="text-decoration: none !important; color: black !important;">
                <div id='filtered_user' class="card-header text-white rounded mt-2" style="background-color: black !important;">{{group}}</div>
            </a>
            {% endfor %} {% endif %}
        </div>

    </div>
</div>

{% endblock %}

templates/other_templates/notifications.html
{% extends 'base.html' %} {% block title %} Etkileşimler {% endblock title %} {% block content %}
<div class='row'>
    <div class='col-md-3'>
    </div>
    <div class='col-md-6 bg-secondary rounded'>
        {% if requests %} {% for request in requests %}
        <div class="row d-flex justify-content-center mt-2 mb-1">
            <div id="friendship_request_box" class="bg-dark text-white">
                <span class="ml-2"><a href="{% url 'User:profile' request.sender %}" class="text-white" style="text-decoration: none !important;">{{request.sender}}</a> kişisinden arkadaşlık isteğin var</span>
                <a href="{% url 'Friendship:accept_request' request.sender %}" class="btn btn-outline-info mr-2">Kabul Et</a>
            </div>
        </div>
        {% endfor %} {% endif %} {% for user in not_seen_message_users %}
        <div class="row d-flex justify-content-center mt-2 mb-1">
            <div id="friendship_request_box" class="bg-dark text-white">
                <span class="ml-2"><a href="{% url 'User:profile' user.username %}" class="text-white" style="text-decoration: none !important;">{{user}}</a> kişisinden okunmamış mesajın var</span>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class='col-md-3'>
    </div>
</div>
{% endblock content %}

templates/other_templates/settings.html
{% extends 'base.html' %} {% load static %} {% block title %} Hedef {% endblock %} {% block content %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div id="custom_user_settings_row" class="col-md-9" style="background-color: rgb(222, 226, 247); height: 100% !important; padding-top: 3% !important;">

            <!--Günlük Görev Hedefi Formu-->
            <div class="row">
                <div class="form-group col-md-6">
                    <h4 class="display-4">Hedef & Verim</h4>
                    <form id="goal_form" method='POST' action="{% url 'goal_create' %}">
                        {% csrf_token %}
                        <div class="goal_section form-inline">
                            <label class="label" for="">Günlük Görev Hedefi: </label>
                            <input name="goal" class="form-control w-25 ml-2" type="number">
                        </div>
                        <button type="submit" class="btn btn-outline-info mt-2">Hedef Belirle</button>
                    </form>
                </div>
                <div class="col-md-6 d-flex align-items-center">
                    <span class="lead  float-left">Şuanki hedef: <b>{{request.user.goal_score}}</b></span>
                </div>
            </div>
            <!--Kategori Formu-->
            <div class="row">
                <div class="form-group col-md-7">
                    <h4 class="display-4 ">Kategori</h4>
                    <form id="category_form" method='POST' action="{% url 'category_create' %}">
                        {% csrf_token %}
                        <div class="category_title_section form-inline ">
                            <label class="label " for=" ">Kategori: </label>
                            <input id="category" name="category" class="form-control w-25 ml-2" type="text">
                        </div>
                        <div class="category_priority_section form-inline mt-3 ">
                            <label class="label" for=" ">Öncelik: </label>
                            <select id="priority" class="form-control ml-3 w-25 " name="priority">
                        <option value="1">1- Mavi</option>
                        <option value="2">2- Yeşil</option>
                        <option value="3">3- Turuncu</option>
                        <option value="4">4- Gri</option>
                        </select>
                            <span class="text-muted ml-2"><small>1- 16 Puan</small><br><small>2- 14 Puan</small><br><small>3- 12 Puan</small><br><small>4- 10 Puan</small></span>
                        </div>
                        <button type="submit" class="btn btn-outline-success mt-2">Kategori Oluştur</button>
                    </form>
                </div>
                <div class="col-md-5 d-flex align-items-center">
                    <ul style="list-style:circle;">
                        {% for category in category_list %}
                        <li class="lead"><b>{{category}}</b></li> {% endfor %}
                    </ul>
                </div>
            </div>
            <!--Reset Bölümü-->
            <h4 class="lead ">Sıfırlama ve Silme</h4>
            <div class="d-inline ">
                <button onclick="CategoryDeleteModal()" class="btn btn-outline-warning mb-3">Kategori Seç ve Sil</button>
                <a href="{% url 'category_list_delete' %}" class="btn btn-outline-warning mb-3">Tüm Kategorileri Sil</a><br>
            </div>
            <div class="d-inline ">
                <a href="{% url 'Task:task_delete_all' slug=request.user %}" class="btn btn-outline-danger">Tüm Görevleri Sil</a>
            </div>

            <!--Kategori Silme Modal-->
            <div class="modal fade" id="categoryDeleteModal" tabindex="-1 " role="dialog " aria-labelledby="taskCreateModalLabel " aria-hidden="true ">
                <div class="modal-dialog" role="document">
                    <div class="modal-content ">
                        <div class="modal-header ">
                            <h5 class="modal-title " id="categoryDeleteModalLabel ">Kategori Sil</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                        </div>
                        <div class="modal-body">
                            <form id="category_delete_form" class="form-group" action="{% url 'category_delete' %}" method="POST">
                                {% csrf_token %}
                                <div class="form-category-delete d-flex form-group mt-4">
                                    {% for category in category_list %}
                                    <div class="row w-100">
                                        <label class="label col-md-9" for="{{category}}">{{category}}</label>
                                        <input id="selected_category" name="selected_category" class="form-control ml-4 col-md-2" value="{{category}}" type="radio">
                                    </div>{% endfor %}
                                </div>
                        </div>
                        <div class="modal-footer ">
                            <button onclick="CategoryDelete()" class="btn btn-primary mb-2">Seçili Kategorileri Sil</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script>
    function CategoryDeleteModal() {
        $('#categoryDeleteModal').modal('show');
    };

    function CategoryDelete() {
        form = $('#category_delete_form');
        form.submit(function(e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                data: form.serialize(),
                url: form.attr('action'),
                success: function(data) {
                    form.submit();
                    location.reload();
                }
            })

        });
    };
</script>
{% endblock %}