Addiction/urls.py
from django.urls import path
from .views import AddictionDetail, AddictionIndex

app_name='Addiction'

urlpatterns = [
    path('index/', AddictionIndex, name='index'),
    path('detail/<slug>/', AddictionDetail, name='detail'),
]

Chat/urls.py
from django.urls import path
from . import views

app_name = 'Chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('start_chat/<str:second_user>', views.start_chat, name='start_chat'),
    path('<str:room_name>/', views.room, name='room'),
    path('message/delete/<int:id>/', views.delete_message, name='delete_message'),
]

Pomodoro/urls.py
from django.urls import path
from .views import PomodoroSettings, PomodoroTimer

app_name = 'Pomodoro'

urlpatterns = [
    path("timer/", PomodoroTimer, name="timer"),
    path("settings/", PomodoroSettings, name="settings"),
]


Task/urls.py
from django.urls import path
from .views import TaskCreate, TaskDelete, TaskIndex, TaskListDelete, TaskUpdate, Done_or_Not

app_name = 'Task'

urlpatterns = [
    path("", TaskIndex, name="index"),
    path("task/create/", TaskCreate, name="task_create"),
    path("task/update/<slug>/", TaskUpdate, name="update"),
    path("task/delete/<slug>/", TaskDelete, name="delete"),
    path("task/delete/all/<slug>/", TaskListDelete, name="task_delete_all"),
    path("task/done_or_not/<slug>/", Done_or_Not, name="done_or_not"),
]

User/urls.py
from .views import CustomUserLogin, RegisterCustomUser, CustomUserProfile, UpdateCustomUser
from django.contrib.auth.views import LogoutView
from django.urls import path

app_name = 'User'

urlpatterns = [
    path('register/', RegisterCustomUser, name = 'register'),
    path('update/<slug>/', UpdateCustomUser, name = 'update'),
    path('profile/<slug>/', CustomUserProfile, name = 'profile'),
    path('login/', CustomUserLogin, name = 'login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name = 'logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import Explore, Notifications, Settings, CategoryCreate, CategoryDelete, CategoryListDelete, GoalCreate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User.urls')),
    path('friendship/', include('Friendship.urls')),
    path('group/', include('Group.urls')),
    path('chat/', include('Chat.urls')),
    path('', include('Task.urls')),
    path('pomodoro/', include('Pomodoro.urls')),
    path('addiction/', include('Addiction.urls')),
    path('explore/', Explore, name = 'explore'),
    path('settings/<slug>/', Settings, name = 'settings'),
    path('notifications/<slug>/', Notifications, name = 'notifications'),
    path('category/create/', CategoryCreate, name = 'category_create'),
    path('category/delete/', CategoryDelete, name = 'category_delete'),
    path('category/list/delete/', CategoryListDelete, name = 'category_list_delete'),
    path('goal/create/', GoalCreate, name = 'goal_create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark" style="background-color: black !important;">
    <div class="container">
        <a href="{% url 'Task:index' %}" class="navbar-brand">WAY TO ACHIEVE</a>
        <button class="navbar-toggler" data-toggle='collapse' data-target='#navbarCollapse'>
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto p-1">
                {% if request.user.is_authenticated %}
                <li class="nav-item mt-1">
                    <a class="nav-link" href="{% url 'Task:index' %}">TODO LIST</a>
                </li>
                <li class="nav-item mt-1">
                    <a class="nav-link" href="{% url 'Pomodoro:settings' %}">POMODORO</a>
                </li>
                <li class="nav-item mt-1">
                    <a class="nav-link" href="{% url 'Chat:index' %}">MESAJLAR</a>
                </li>
                <li class="nav-item {% if notification_count %}form-inline {% else %}mt-1{% endif %}">
                    <a class="nav-link" href="{% url 'notifications' request.user.username %}">ETKİLEŞİMLER</a> {% if notification_count %}
                    <span id="notification_count" class="bg-info text-white rounded-circle d-flex justify-content-center h-50"><span class="mr-1">{{notification_count}}</span></span>
                    {% endif %}
                </li>
                <li class="nav-item mt-1 ">
                    <a class="nav-link " href="{% url 'Addiction:index' %} ">YENİLEN</a>
                </li>
                <li class="nav-item mt-1 ">
                    <a class="nav-link " href="{% url 'explore' %} ">KEŞİF</a>
                </li>
                {% if request.user.avatar == 'avatar/default.png' %}
                <li class="nav-item ml-1 mt-1 ">
                    <a href="{{request.user.profile_set.get.get_absolute_url}} " class="nav-link ">PROFİL</a>
                </li>
                {% else %}
                <li class="nav-item ml-3 " style="margin-top: -0.6% !important; ">
                    <a id="avatar " href="{{request.user.profile_set.get.get_absolute_url}} "><img class="rounded-circle " style="width: 50px !important; height: 50px !important; " src="{{request.user.avatar.url}} " alt=" "></a>
                </li>
                {% endif %} {% elif not request.user.is_authenticated %}
                <li class="nav-item mt-1 ">
                    <a class="nav-link " href="{% url 'User:login' %} ">GİRİŞ YAP</a>
                </li>
                <li class="nav-item mt-1 ">
                    <a class="nav-link " href="{% url 'User:register' %} ">KAYIT OL</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>